
language: generic
dist: bionic
sudo: false
cache:
  directories:
    - ~/arduino_ide
    - ~/.arduino15/packages/

before_install:
   - wget -c https://files.seeedstudio.com/arduino/seeed-arduino-ci.sh

script:
   - chmod +x seeed-arduino-ci.sh
   - cat $PWD/seeed-arduino-ci.sh
   - bash $PWD/seeed-arduino-ci.sh  Iot_IR:seeed_XIAO_m0/Iot_IR:uno/servo:seeed_XIAO_m0/servo:uno/rawSend:seeed_XIAO_m0/rawSend:uno/serialRemote:seeed_XIAO_m0/serialRemote:uno arduino-libraries/Servo arduino-libraries/Mouse arduino-libraries/Keyboard

notifications:
  email:
    on_success: change
    on_failure: change
